### ISSUE TITLE
Add Infro PR Checks?

### ISSUE THREAD

**Issue by colethienes** [hashbang/gitops#259]
I noticed that this repo uses Argo CD, and I thought I’d let you know that I recently released a Github app called Infro that several companies use internally that allows Argo CD users to preview Kubernetes changes in Github pull requests before they merge. I’m providing it for free to open source projects ([here’s](https://github.com/broersma-forslund/homelab/pull/158#issuecomment-1962289857) an example in the wild). [Here’s](https://medium.com/@colethienes/argocd-pull-request-checks-c863190c5f8c?source=friends_link&sk=2eda79520de33483591448c6dfe8d284) a setup guide with links to documentation. It’s in early stages, so I’m sure there will be warts. All feedback is welcome!

**Comment by daurnimator** [comment]
@colethienes interesting. I wanted to give it a try but I don't agree to the permissions

![image](https://github.com/hashbang/gitops/assets/127971/0e164a75-338a-494c-8128-ee8573e528dc)

"Act on your behalf" is too broad and I wouldn't ever agree to that.

**Comment by colethienes** [comment]
I open sourced a version as a GitHub action here! https://github.com/infro-io/infro-core?tab=readme-ov-file#as-a-github-action

**Comment by daurnimator** [comment]
> I open sourced a version as a GitHub action here! https://github.com/infro-io/infro-core?tab=readme-ov-file#as-a-github-action

I had a quick look and saw https://github.com/infro-io/comment-diffs-action/issues/1 as a problem

**Comment by daurnimator** [comment]
@colethienes added.

In https://github.com/hashbang/gitops/pull/251#issuecomment-2367456229 I can see it shows diffs from live cluster to repo. The live cluster might not currently be at the previous HEAD. This can make the PR comment pretty misleading
