### ISSUE TITLE
Enable CRDs for cert-manager Helm chart

### ISSUE THREAD

**Issue by RyanSquared** [hashbang/gitops#46]
Requires kubectl version 1.18.8+ (about, I didn't do thorough testing, but definitely not 1.18.3).

**Comment by RyanSquared** [comment]
Alternative solution to using the Helm chart is that I've extracted the resources and made them into a Kustomization here: https://github.com/RyanSquared/gitops/tree/master/cert-manager

The issue will still exist until ArgoCD gets a new kubectl.

**Comment by daurnimator** [comment]
> Requires kubectl version 1.18.8+ (about, I didn't do thorough testing, but definitely not 1.18.3).

What feature of 1.18.8 is required?

**Comment by RyanSquared** [comment]
> What feature of 1.18.8 is required?

kubectl blocks on checking whether or not CRDs need to be reconfigured in prior versions. When talking in the ArgoCD slack, someone there mentioned it should be as simple as FROM'ing the argocd container and ADD'ing in a working version of kubectl.

**Comment by daurnimator** [comment]
done via 7a657b5
