### ISSUE TITLE
Hook up alertmanager to IRC

### ISSUE THREAD

**Issue by daurnimator** [hashbang/gitops#59]
https://github.com/google/alertmanager-irc-relay

Probably have alerts go to a channel for that purpose (e.g. `#!infra` ? )

**Comment by RyanSquared** [comment]
> Probably have alerts go to a channel for that purpose (e.g. #!infra ? )

I am thinking of moving hashbang/gitops GitHub messages, ArgoCD messages, and alerts go into that channel. Any issue with this?

**Comment by daurnimator** [comment]
> I am thinking of moving hashbang/gitops GitHub messages, ArgoCD messages, and alerts go into that channel. Any issue with this?

Sounds good to me.

**Comment by daurnimator** [comment]
see also https://github.com/google/alertmanager-irc-relay/issues/8

**Comment by RyanSquared** [comment]
An alternative solution is to have all webhooks point to BitBot and get an integration set up for that. That way, we can have a somewhat central platform to point webhooks at. We don't manage our own BitBot instance at this point but it shouldn't be too hard to set up.

**Comment by daurnimator** [comment]
https://github.com/google/alertmanager-irc-relay/issues/8#issuecomment-722468724 is now fixed :)

**Comment by daurnimator** [comment]
monitoring is gone now.
